import "~/styles/globals.css";

import { type Metadata } from "next";
import { TopNavigation } from "./_components/topnavigation";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans`}>
        <div className="grid h-screen grid-rows-[auto,1fr]">
          <TopNavigation />
          <main className="overflow-y-scroll">{children}</main>
        </div>
        {modal}

        <div id="modal-root" />
      </body>
    </html>
  );
}
