import "~/styles/globals.css";

import { type Metadata } from "next";
import { TopNavigation } from "./_components/topnavigation";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`dark flex-col gap-4 font-sans`}>
        <div className="grid h-screen grid-rows-[auto,1fr]">
          <TopNavigation />
          {children}
          {modal}
        </div>
        <div id="modal-root" />
      </body>
    </html>
  );
}
